---
version: "3"

networks:
  ranchat-grafana:

services:
  grafana:
    build:
      context: ./grafana
    user: root
    ports:
      - "3000:3000"
    volumes:
     - ./grafana/storage:/var/lib/grafana:rw,Z
    networks:
      - ranchat-grafana

  loki:
    image: grafana/loki:2.7.1
    environment:
      - IAM_LOKI_ACCESS_KEY=${IAM_LOKI_ACCESS_KEY}
      - IAM_LOKI_SECRET_KEY=${IAM_LOKI_SECRET_KEY}
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - "3100:3100"
      - "7946:7946"
      - "9095:9095"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ranchat-grafana

  gateway:
    build:
      context: ./gateway
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ranchat-grafana
    depends_on:
      - grafana
      - loki
